---
# This playbook deploys the whole application stack in this site.

- name: Apply a common configuration to all artifactoryservers nodes
  hosts: artifactoryservers
  remote_user: {{ required_remote_user }}

  roles:
    - common