# Artifactory RPM Installation playbook
# ==========================
# Artifactory can also be installed from an RPM or Debian distribution on Red Hat compatible Linux distributions.
# The installation package creates a dedicated user, installs a stripped-down distribution of the Apache Tomcat container configured for Artifactory (on port 8081), and registers this Tomcat as a service (but does not start it immediately).
# Iteration 1 - get ansible working and install artifactory RPM and dependencies.
#           2 - modify configuration files to use mysql server.
#           3 - modify configuration files to use attach storage.

- name: Download and install dependency - Java
  become: yes
  become_method: sudo
  yum:
    name: {{ required_java_version }}
    state: latest
  tags:
    - artifactory

- name: Check dependency - Java
  action: shell /usr/bin/java -version
  register: java
  changed_when: no
  tags:
    - artifactory
- assert:
    that:
      - "'version' in java.stderr"

- name: Download artifactory repo file
  become: yes
  become_method: sudo
  get_url:
    url: "https://bintray.com/jfrog/artifactory-pro-rpms/rpm"
    dest: /etc/yum.repos.d/bintray-jfrog-artifactory-pro-rpms.repo

  tags:
    - artifactory

- name: Install the latest version of Artifactory
  become: yes
  become_method: sudo
  yum:
    name: {{ required_artifactory_version }}
    state: latest
  tags:
    - artifactory

- name: Enable the artifactory service
  become: yes
  become_method: sudo
  service:
    name: artifactory
    enabled: true
  tags:
    - artifactory


# MySQL
# Assumes RDS already created. Default is Derby Storage, and this works out of the box.

# Attach EBS Storage
# Assumes EBS already created.
# Default is local storage, and this works out of the box.
